name: "mySecondJekyllSite"
description: "my description"

source: .
destination: _site

url: "http://laurin2001.github.io/mySecondJekyllSite/"
baseurl: "/mySecondJekyllSite"

paginate: 10

#comment

markdown: rdiscount
permalink: pretty
pygments: true
